version: 2

defaults: &defaults
  working_directory: ~/workspace
  docker:
    - image: circleci/node:12.16.3

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install
      - run: yarn bootstrap
      - run:
          name: Run tests
          command: yarn test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - persist_to_workspace:
          root: ~/workspace
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/workspace/.npmrc
      - run:
          name: Publish packages
          command: yarn publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
