name: "🚀 publish"

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: 🚀 publish
    runs-on: ubuntu-latest
    steps:
      - name: 📚 checkout
        uses: actions/checkout@v4.1.7
      - name: 🟢 node
        uses: actions/setup-node@v4.0.3
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: install restalize packages
        working-directory: ./packages/restalize
        run: yarn
        env:
          NODE_ENV: development
      - name: install restalize-template packages
        working-directory: ./packages/restalize-template
        run: yarn
        env:
          NODE_ENV: development
      - name: 🧪 test
        run: yarn test
      - name: 🚀 publish
        run: yarn deploy
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
